server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - http://localhost:5173
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                exposed-headers: "*"
                allow-credentials: true
                max-age: 3600
          routes:
            - id: auth-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/auth/**

            - id: category-taxonomy-by-post
              uri: http://localhost:8084
              predicates:
                - Path=/api/posts/*/taxonomy

            - id: post-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/posts/**

            - id: comment-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/comments/**

            - id: category-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/categories/**,/api/tags/**,/api/post-categories/**,/api/post-tags/**
              filters:
                - RewritePath=/api/categories/api/categories/?(?<segment>.*), /api/categories/$\{segment}
                - RewritePath=/api/categories/api/tags/?(?<segment>.*), /api/tags/$\{segment}

            - id: media-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/media/**,/files/**
              filters:
                - RewritePath=/api/media/api/media/?(?<segment>.*), /api/media/$\{segment}

            - id: notification-service
              uri: http://localhost:8087
              predicates:
                - Path=/api/notifications/**,/notification-api/**
              filters:
                - RewritePath=/api/notifications/api/notifications/?(?<segment>.*), /api/notifications/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

info:
  app:
    name: InkWell API Gateway
    description: Single public entry point for InkWell microservices
    version: 1.0.0
