server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
          routes:
            - id: auth-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/auth/**

            - id: category-taxonomy-by-post
              uri: http://localhost:8084
              predicates:
                - Path=/api/posts/*/taxonomy

            - id: post-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/posts/**

            - id: comment-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/comments/**

            - id: category-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/categories/**,/api/tags/**,/api/post-categories/**,/api/post-tags/**

            - id: media-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/media/**,/files/**

            - id: notification-service
              uri: http://localhost:8087
              predicates:
                - Path=/api/notifications/**,/notification-api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

info:
  app:
    name: InkWell API Gateway
    description: Single public entry point for InkWell microservices
    version: 1.0.0
